apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-ml-app
  labels:
    app: weather-ml-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-ml-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: weather-ml-app
    spec:
      containers:
      - name: weather-ml-app
        image: 13mj/weather-ml-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

